### PR TITLE
export simulate & clippy nursery

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
I plan to implement the simulator in Anki, so I need to export `simulate` at first.

### CODE REVIEW

**Review by asukaminato0721 — APPROVED** [review]

**Comment by dae** [comment]
There's a fair bit that's been made public here - are you intending to make all of the exposed public options/methods be used in Anki, or did you add pub to the other methods to get things to compile? If you only need to use a subset of these in Anki, it might be cleaner to make a new public method that only exposes the things that should be changed, and then the rest can be kept private.

**Comment by L-M-Sherlock** [comment]
> There's a fair bit that's been made public here

The clippy::nursery outputs a lot of errors like:

```
error: pub(crate) struct inside private module
   --> src/dataset.rs:136:1
    |
136 | pub(crate) struct FSRSDataset {
    | ----------^^^^^^^^^^^^^^^^^^^
    | |
    | help: consider using: `pub`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate
    = note: `-D clippy::redundant-pub-crate` implied by `-D clippy::nursery`
    = help: to override `-D clippy::nursery` add `#[allow(clippy::redundant_pub_crate)]`
```

So I guess most of them are still private?

**Comment by L-M-Sherlock** [comment]
> are you intending to make all of the exposed public options/methods be used in Anki

I only want to expose those options/methods declared in

https://github.com/open-spaced-repetition/fsrs-rs/blob/b82777178ea4c4f6aa82c4fe0432d9ce8b8802e2/src/lib.rs#L18-L25

**Comment by dae** [comment]
If so, can't you remove pub from the items not listed there?

```diff
diff --git a/src/batch_shuffle.rs b/src/batch_shuffle.rs
index df4b703..cfc72ee 100644
--- a/src/batch_shuffle.rs
+++ b/src/batch_shuffle.rs
@@ -13,7 +13,7 @@ use std::{
 
 use crate::{dataset::FSRSDataset, FSRSItem};
 
-pub struct BatchShuffledDataset<I> {
+pub(crate) struct BatchShuffledDataset<I> {
     dataset: Arc<FSRSDataset>,
     indices: Vec<usize>,
     input: PhantomData<I>,
diff --git a/src/cosine_annealing.rs b/src/cosine_annealing.rs
index 95751c0..325acf1 100644
--- a/src/cosine_annealing.rs
+++ b/src/cosine_annealing.rs
@@ -1,6 +1,6 @@
 use burn::{lr_scheduler::LrScheduler, tensor::backend::Backend, LearningRate};
 #[derive(Clone, Debug)]
-pub struct CosineAnnealingLR {
+pub(crate) struct CosineAnnealingLR {
     t_max: f64,
     eta_min: f64,
     init_lr: LearningRate,
diff --git a/src/dataset.rs b/src/dataset.rs
index 47cb3b2..82ec6e8 100644
--- a/src/dataset.rs
+++ b/src/dataset.rs
@@ -50,7 +50,7 @@ impl FSRSItem {
     }
 }
 
-pub struct FSRSBatcher<B: Backend> {
+pub(crate) struct FSRSBatcher<B: Backend> {
     device: B::Device,
 }
 
@@ -61,7 +61,7 @@ impl<B: Backend> FSRSBatcher<B> {
 }
 
 #[derive(Debug, Clone)]
-pub struct FSRSBatch<B: Backend> {
+pub(crate) struct FSRSBatch<B: Backend> {
     pub t_historys: Tensor<B, 2, Float>,
     pub r_historys: Tensor<B, 2, Float>,
     pub delta_ts: Tensor<B, 1, Float>,
@@ -133,7 +133,7 @@ impl<B: Backend> Batcher<FSRSItem, FSRSBatch<B>> for FSRSBatcher<B> {
     }
 }
 
-pub struct FSRSDataset {
+pub(crate) struct FSRSDataset {
     items: Vec<FSRSItem>,
 }
 
diff --git a/src/inference.rs b/src/inference.rs
index ad2d57e..4d5b64f 100644
--- a/src/inference.rs
+++ b/src/inference.rs
@@ -13,10 +13,10 @@ use crate::model::Model;
 use crate::training::BCELoss;
 use crate::{FSRSError, FSRSItem};
 use burn::tensor::ElementConversion;
-pub const DECAY: f64 = -0.5;
+pub(crate) const DECAY: f64 = -0.5;
 /// (9/10) ^ (1 / DECAY) - 1
-pub const FACTOR: f64 = 19f64 / 81f64;
-pub const S_MIN: f32 = 0.01;
+pub(crate) const FACTOR: f64 = 19f64 / 81f64;
+pub(crate) const S_MIN: f32 = 0.01;
 /// This is a slice for efficiency, but should always be 17 in length.
 pub type Parameters = [f32];
 use itertools::izip;
diff --git a/src/model.rs b/src/model.rs
index 19b7f16..08ef3cd 100644
--- a/src/model.rs
+++ b/src/model.rs
@@ -16,7 +16,7 @@ pub struct Model<B: Backend> {
     pub config: ModelConfig,
 }
 
-pub trait Get<B: Backend, const N: usize> {
+pub(crate) trait Get<B: Backend, const N: usize> {
     fn get(&self, n: usize) -> Tensor<B, N>;
 }
 
@@ -177,7 +177,7 @@ impl<B: Backend> Model<B> {
 }
 
 #[derive(Debug, Clone)]
-pub struct MemoryStateTensors<B: Backend> {
+pub(crate) struct MemoryStateTensors<B: Backend> {
     pub stability: Tensor<B, 1>,
     pub difficulty: Tensor<B, 1>,
 }
@@ -240,7 +240,7 @@ impl<B: Backend> FSRS<B> {
     }
 }
 
-pub fn parameters_to_model<B: Backend>(parameters: &Parameters) -> Model<B> {
+pub(crate) fn parameters_to_model<B: Backend>(parameters: &Parameters) -> Model<B> {
     let config = ModelConfig::default();
     let mut model = Model::new(config);
     model.w = Param::from(Tensor::from_floats(
diff --git a/src/pre_training.rs b/src/pre_training.rs
index a3ae59a..872c1dc 100644
--- a/src/pre_training.rs
+++ b/src/pre_training.rs
@@ -106,7 +106,7 @@ fn loss(
     logloss + l1
 }
 
-pub const INIT_S_MAX: f32 = 100.0;
+pub(crate) const INIT_S_MAX: f32 = 100.0;
 
 fn search_parameters(
     mut pretrainset: HashMap<FirstRating, Vec<AverageRecall>>,
diff --git a/src/training.rs b/src/training.rs
index 65a57d5..c736742 100644
--- a/src/training.rs
+++ b/src/training.rs
@@ -112,7 +112,7 @@ impl CombinedProgressState {
         self.splits.iter().map(|s| s.total()).sum()
     }
 
-    pub const fn finished(&self) -> bool {
+    pub fn finished(&self) -> bool {
         self.finished
     }
 }
@@ -166,7 +166,7 @@ impl MetricsRenderer for ProgressCollector {
 }
 
 #[derive(Config)]
-pub struct TrainingConfig {
+pub(crate) struct TrainingConfig {
     pub model: ModelConfig,
     pub optimizer: AdamConfig,
     #[config(default = 5)]
diff --git a/src/weight_clipper.rs b/src/weight_clipper.rs
index 0c475ec..13e2df0 100644
--- a/src/weight_clipper.rs
+++ b/src/weight_clipper.rs
@@ -4,7 +4,7 @@ use crate::{
 };
 use burn::tensor::{backend::Backend, Data, Tensor};
 
-pub fn weight_clipper<B: Backend>(parameters: Tensor<B, 1>) -> Tensor<B, 1> {
+pub(crate) fn weight_clipper<B: Backend>(parameters: Tensor<B, 1>) -> Tensor<B, 1> {
     let val = clip_parameters(&parameters.to_data().convert().value);
     Tensor::from_data(
         Data::new(val, parameters.shape()).convert(),
@@ -12,7 +12,7 @@ pub fn weight_clipper<B: Backend>(parameters: Tensor<B, 1>) -> Tensor<B, 1> {
     )
 }
 
-pub fn clip_parameters(parameters: &Parameters) -> Vec<f32> {
+pub(crate) fn clip_parameters(parameters: &Parameters) -> Vec<f32> {
     // https://regex101.com/r/21mXNI/1
     const CLAMPS: [(f32, f32); 17] = [
         (S_MIN, INIT_S_MAX),
```

**Comment by L-M-Sherlock** [comment]
Perhaps I misunderstand the suggestion of `clippy::nursery`. But the following error is thrown when I remove the `pub`:

```
error[E0603]: struct `CosineAnnealingLR` is private
 --> src/training.rs:2:30
  |
2 | use crate::cosine_annealing::CosineAnnealingLR;
  |                              ^^^^^^^^^^^^^^^^^ private struct
  |
note: the struct `CosineAnnealingLR` is defined here
 --> src/cosine_annealing.rs:3:1
  |
3 | struct CosineAnnealingLR {
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by L-M-Sherlock** [comment]
I learn something about the `pub(crate)` and modules in Rust. The documents said that it makes not difference between `pub` and `pub(crate)` if the module is private.

**Comment by dae** [comment]
Clippy nursery checks have not been marked as stable yet, and there can be downsides/bugs with some of them. In this case, pub(crate) is the best option, as it a) allows the function to be used in other Rust files inside fsrs-rs, and b) it ensures we don't accidentally make the function public in the future if the module is made public. So I think the correct action here would be to revert those changes, and then disable that nursery lint.

**Comment by L-M-Sherlock** [comment]
OK. I will revert unnecessary modifications soon.

**Comment by dae** [comment]
No need for a new release for this, it can wait until a future update.

**Pull request merged**
