### PR TITLE
Fix/check review_limit only if is_learn is false

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
fix https://github.com/ankitects/anki/issues/3654

### CODE REVIEW

**Review by Luc-Mcgrady — APPROVED** [review]
That issue is talking about this option
image

which defaults to off though in the simulator defaults to on.

image

To fix it you would need to add that to the simulator config.
something like.

```rs
let review_learn_count = learn_cnt_per_day[day_index] * (config.new_cards_affect_review_limit ? 1 : 0) 
if (!is_learn && review_cnt_per_day[day_index] + review_learn_count + 1 > review_limit)
    || (is_learn && learn_cnt_per_day[day_index] + 1 > learn_limit)
    || (cost_per_day[day_index] + fail_cost > max_cost_perday)
```

I originally made it default to off in the simulator:
https://github.com/open-spaced-repetition/fsrs-rs/pull/235/files/a79f4221e3652aedd940720b77ad0774407da736..cbe8f9d98f75189445d90435ec7339e900b01fa0#r1798205551
 
This is still a bug though I'm pretty sure :smile:

**Comment by L-M-Sherlock** [comment]
OK, so we should make a breaking change?

**Comment by Luc-Mcgrady** [comment]
This does actually fix this issue nvm.

I'm not sure its worth the breaking change, maybe if another breaking change happens we can include it then.

**Comment by L-M-Sherlock** [comment]
I tend to merge this PR and keep the breaking change in the future. What do you think of?

**Comment by Luc-Mcgrady** [comment]
Sounds good

**Pull request merged**
