### PR TITLE
Feat/float next interval

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Related PR:

- https://github.com/ankitects/anki/pull/3375

### CODE REVIEW

**Comment by dae** [comment]
These changes look pretty straightforward. I presume we could retain the same behavior on Anki's end, if desired, by rounding the intervals on that side? Is your intention to do that for 1+ day intervals, and treat subday intervals differently if there are no (re)learning steps?

**Comment by L-M-Sherlock** [comment]
Yes. In the corresponding PR, I modified the code to round the interval and make sure it's greater or equal to 1 day. For interval shorter than 0.5 day, if there are no (re)learning steps, it will be converted to seconds.

**Comment by dae** [comment]
FSRS controlling subday intervals is a bit contentious, but we can discuss that in the linked PR - looks like the changes here should be ok to merge?

**Comment by L-M-Sherlock** [comment]
It's OK to merge this PR. But it's nice if we can wait for merging #222, which doesn't need Anki side to change the code. This PR is not back-compatible, if I merge it first, I have to update a bunch of code in Anki side.

**Comment by L-M-Sherlock** [comment]
I recommend merging this PR https://github.com/ankitects/anki/pull/3405 first.

**Comment by L-M-Sherlock** [comment]
@dae, do you approve this PR?

**Review by dae — APPROVED** [review]

**Pull request merged**
