### PR TITLE
update to 0.13.1

### PR DESCRIPTION
**Pull request by AlexErrant**
With this PR and [the other](https://github.com/open-spaced-repetition/burn/pull/2), fsrs-browser passes its tests.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Is it OK to Squash and merge this PR? Or you prefer to rebase or merge commit?

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by AlexErrant** [comment]
I'm okay with whatever you prefer!

**Comment by AlexErrant** [comment]
Just checking - is there a reason why there's an [empty commit](https://github.com/open-spaced-repetition/fsrs-rs/commit/16bdf86c5053038dd6fc9bf939f395b889be9fe2)? I know you prefer minimalism, so just checking.

**Comment by L-M-Sherlock** [comment]
> Just checking - is there a reason why there's an [empty commit](https://github.com/open-spaced-repetition/fsrs-rs/commit/16bdf86c5053038dd6fc9bf939f395b889be9fe2)? I know you prefer minimalism, so just wondering.

The GitHub action doesn't work, so I merge the main branch into fsrs-browser manually in my local device. It generated the empty commit.

**Comment by AlexErrant** [comment]
> so I merge the main branch into fsrs-browser manually in my local device

I believe it failed because

```
Already on 'fsrs-browser'
Your branch is up to date with 'origin/fsrs-browser'.
Already up to date.
```

https://github.com/open-spaced-repetition/fsrs-rs/actions/runs/8733011449/job/23960915778#step:5:33

Which is why the merge commit was empty. I _think_ if I add `--no-ff ` to the git command it will _not_ fast-forward and generate merge commits as you did. [The original article](https://medium.com/@karlstad/create-a-github-actions-workflow-that-auto-merges-the-master-back-to-dev-branch-8b1ebe7009b3) uses this. I removed it because I thought you would prefer it. I can add it back if you want :) also please don't hesitate to @ me if that action doesn't do what you want.

**Comment by L-M-Sherlock** [comment]
> Which is why the merge commit was empty. I _think_ if I add `--no-ff ` to the git command it will _not_ fast-forward and generate merge commits as you did. [The original article](https://medium.com/@karlstad/create-a-github-actions-workflow-that-auto-merges-the-master-back-to-dev-branch-8b1ebe7009b3) uses this. I removed it because I thought you would prefer it. I can add it back if you want :)

Could you add it back? Thanks!

**Pull request merged**
