### PR TITLE
Fix/simulator crashes if no history

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
source: https://forums.ankiweb.net/t/fsrs-simulator-crashes-anki-if-no-history/48541

### CODE REVIEW

**Review by asukaminato0721 — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
@dae should we introduce a new kind of error? Or just return zeros in the simulation result?

**Comment by dae** [comment]
Sorry for the delay. I don't have a strong preference here. One way would be to reuse InvalidInput, and mention in the docstring that deck size is expected to be non-zero (as 0 is nonsensical) - effectively making it the caller's responsibility to check. We could combine that with a tweak on Anki's side so that the size input can't go below 1.

For cases where existing cards > deck size, would it make sense to cap existing cards to the provided value?

**Comment by dae** [comment]
(adding a new error is a valid approach too - I just tend to lump rare/invalid inputs into InvalidInput out of convenience)

**Comment by L-M-Sherlock** [comment]
Sorry for slow response. I'm still in traveling. Here are some my thoughts:

> One way would be to reuse InvalidInput, and mention in the docstring that deck size is expected to be non-zero (as 0 is nonsensical) - effectively making it the caller's responsibility to check.

Sounds good. I will check the code and try to reuse InvalidInput.

> For cases where existing cards > deck size, would it make sense to cap existing cards to the provided value?

Deck size is equal to the number of existing cards plus the number of additional new cards. So existing cards > deck size is invalid because the number of additional new cards should be greater than or equal to zero.

**Comment by dae** [comment]
> Sorry for slow response. I'm still in traveling. Here are some my thoughts:

Not a problem; I hope you're having fun. :-)

> So existing cards > deck size is invalid because the number of additional new cards should be greater than or equal to zero.

Just wondering how much effort we need to be putting into handling non-sensical cases. If we anticipate it to be a common cause of confusion, a separate message to the user about how it doesn't make sense could work. But if this is going to be pretty rare, a simpler solution like clamping the value or returning 0s might be fine too.

**Pull request merged**
