### PR TITLE
Update burn

### PR DESCRIPTION
**Pull request by dae**
The first commit should fix the old dependency issues.

The second commit is for discussion, and I'm happy to change it if you prefer the old way.

-  do either of you currently use the experiment.log or checkpoint file outputs in the artifact dir? Or even the config.json? If not, we may gain a small performance boost by not writing those files - especially experiment.log, which can be quite big.
- the new train CLI is a bit distracting when running tests. What do you think about hiding progress when the tests are run, as I've done in the second commit?

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
> * do either of you currently use the experiment.log or checkpoint file outputs in the artifact dir?

I only use the experiment.log and checkpoint file for debugging.

**Comment by dae** [comment]
Do you use it frequently enough that you'd like it on by default, or would you be happy to do something like 'cargo test --release --features log' when you need it?

**Comment by dae** [comment]
or maybe LOG=1 cargo test --release

**Comment by L-M-Sherlock** [comment]
Yeah, it's OK. By the way, I couldn't find the log file when I use Anki fsrs branch for test. Does it mean that it doesn't write anything?

**Comment by dae** [comment]
Yeah, I turned it off for Anki, since we don't need it. But if you'd find it useful, I could make it configurable via an env var.

**Comment by L-M-Sherlock** [comment]
It's better to make it configurable. `NaN` doesn't raise error in the model, so it's hard to locate the bug if we doesn't have the log file during the training.

**Comment by dae** [comment]
Ok, I'll update this PR

**Comment by dae** [comment]
Do you have a preference as to whether the text goes to stdout or a file? With an env var like:

`RUST_LOG=debug ./run`, you could see the text in real time on the terminal, or use `RUST_LOG=debug ./run | tee file` if you also wanted to save it to a file.

**Comment by L-M-Sherlock** [comment]
> Do you have a preference as to whether the text goes to stdout or a file?

I prefer to output them in file, because the training process often generates tons of logs, which will flood the terminal.

**Comment by dae** [comment]
Does that work for you? It should work in Anki too, once I update it.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM.

Usage:

```rust
BURN_LOG=tmp/fsrs cargo test --release
```

**Pull request merged**
