### PR TITLE
A couple of minor fixes

### PR DESCRIPTION
**Pull request by dae**
Issues I noticed while integrating the latest changes into Anki. The rename would also be appreciated when merging this in :pray:

### CODE REVIEW

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by dae** [comment]
Thanks Jarrett. I'm going to try integrating the reviewing portion over the coming days.

**Comment by L-M-Sherlock** [comment]
> I'm going to try integrating the reviewing portion over the coming days.

There are some exceptional cases to deal with in re-calculate the stability. Such as `set due date`, `forget`, `incomplete revlogs` and so on. I have written some code to handle them. It would be helpful to you:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/a26bc62148f4c09db1c9dab508d8ea79413c0244/schedule/reschedule.py#L367-L453

**Comment by dae** [comment]
To start with, I'm focusing on updating s/d when weights are changed, and integrating next_states() into the Anki scheduler. Once the basics are done, we can look into those other cases. It would be helpful if you could briefly describe the issues you faced, as that would help me follow what the code is trying to do.

**Comment by L-M-Sherlock** [comment]
I opened a new issue to collect these cases:
- #63

**Pull request merged**
