### PR TITLE
Support overriding initial S/D when revlog incomplete

### PR DESCRIPTION
**Pull request by dae**
https://github.com/open-spaced-repetition/fsrs-rs/issues/87

### CODE REVIEW

**Comment by user1823** [comment]
@dae, thanks for implementing this. I just wanted to confirm one thing. After this change, the incomplete review history would be used for calculating the memory states but not for training. Right?

**Comment by dae** [comment]
Correct.

**Comment by L-M-Sherlock** [comment]
I have a point need to confirm: when the incomplete revlog has N revlog entry (e.g. 1...N), the first revlog will be converted to the start memory state, and the remaining revlogs' intervals and ratings are converted to t_history and r_history, right? The rating of the first review is irrelevant here.

**Comment by dae** [comment]
I think this is something I'll need to handle on Anki's end - does the clarified docstring answer your question?

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
