### PR TITLE
Feat/minimal workload for optimal retention

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
- https://github.com/open-spaced-repetition/optimal-desired-retention/blob/main/notebook.ipynb
- https://github.com/open-spaced-repetition/fsrs-optimizer/pull/89

I refactor the approach to calculate the optimal retention. Now the optimizer will output the optimal retention to minimize the workload/cost per memorization.

image

Ideally, the user only needs to input `learn_span` in the new optimizer for retention. So it's easier to use than the previous implementation.

image

By the way, we may notice users that desired retention <  optimal retention is worse than desired retention > optimal retention. Because the former means **less** memorization & **more** workload and the latter means **more** memorization & **more** workload.

### CODE REVIEW

**Review by asukaminato0721 — APPROVED** [review]

**Comment by dae** [comment]
So we can remove deck size and minutes/day, but I presume we still need to expose the daily new and review limits?

**Comment by dae** [comment]
Sorry, to confirm, do you mean we should not add either? Or do you mean we should just add the new limit?

**Comment by L-M-Sherlock** [comment]
We only need `Days to simulate`. I have made necessary modifications in Anki's part in the PR.

**Comment by dae** [comment]
This is still in simulator config:

```
    pub learn_limit: usize,
    pub review_limit: usize,
```

Would it make sense to remove these in the future? (not urgent)

**Comment by L-M-Sherlock** [comment]
> Would it make sense to remove these in the future? (not urgent)

Yeah it's still in simulator config because they are useful if we want to provide built-in simulator in the future. They are just useless in optimizing the retention.

**Pull request merged**
