### PR TITLE
Increase the sample size.rs

### PR DESCRIPTION
**Pull request by Expertium**
Since the new method is roughly 2 times faster, how about sacrificing that speed in favor of accuracy? Of course, ideally we want both, but if I had to choose, I would say accuracy is more important in this case.
After this change, the speed should be more or less the same as with the old method.

### CODE REVIEW

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by Expertium** [comment]
@L-M-Sherlock I think there is an error in this line:
`let (mut a, mut b) = (xa.min(xc), xa.max(xc));`
Original Python code:
```
    if xa < xc:
        a = xa
        b = xc
    else:
        a = xc
        b = xa
```

**Comment by izik1** [comment]
that looks correct and equivalent to:
```rs
let (mut a, mut b) = if xa < xc { (xa, xc) } else { (xc, xa) };
```

**Comment by L-M-Sherlock** [comment]
> `let (mut a, mut b) = (xa.min(xc), xa.max(xc));`

This code is correct. a is the minimum between xa and xc, and b is the maximum between xa and xc.

**Comment by Expertium** [comment]
By the way, how can I tell whether this is implemented in the new beta?

**Comment by dae** [comment]
Check which fsrs-rs commit Anki currently points to: https://github.com/ankitects/anki/blob/edd38ca06730d7fc16804f52ce10f6bc54c3d145/Cargo.toml#L39

**Pull request merged**
